# Generated by Django 4.1 on 2023-12-10 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_student",
            new_name="is_contentCreator",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_teacher",
            new_name="is_sponsor",
        ),
    ]
