# Generated by Django 4.1 on 2023-12-26 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0003_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channelname", models.CharField(max_length=200)),
                ("total_subscriber", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                ("contactinfo", models.TextField(blank=True, null=True)),
                ("contentstyle", models.TextField(blank=True, null=True)),
                ("publish", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
