# Generated by Django 4.1 on 2023-12-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0004_user_image_businessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcreator",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentcreator",
            name="channelname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contentcreator",
            name="contactinfo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentcreator",
            name="contentstyle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentcreator",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentcreator",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentcreator",
            name="total_subscriber",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="organizationname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name="BusinessProfile",
        ),
    ]
