# Generated by Django 4.1 on 2023-12-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0005_contentcreator_about_contentcreator_channelname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcreator",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
