# Generated by Django 4.1 on 2023-12-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_contentcreator_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcreator",
            name="bitmessage",
            field=models.TextField(blank=True, null=True),
        ),
    ]
