# Generated by Django 4.1 on 2023-12-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0007_contentcreator_bitmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentcreator",
            name="bitmessage",
        ),
        migrations.CreateModel(
            name="BitMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitmessage", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myApp.contentcreator",
                    ),
                ),
            ],
        ),
    ]
