# Generated by Django 4.1 on 2023-12-26 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0008_remove_contentcreator_bitmessage_bitmessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BitMessage",
            new_name="BidMessage",
        ),
        migrations.RenameField(
            model_name="bidmessage",
            old_name="bitmessage",
            new_name="bidmessage",
        ),
    ]
