# Generated by Django 4.1 on 2024-05-28 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0009_rename_bitmessage_bidmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidmessage",
            name="user1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myApp.sponsor",
            ),
        ),
    ]
