# Generated by Django 4.1 on 2024-05-28 04:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0010_bidmessage_user1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg", models.TextField(blank=True, null=True)),
                (
                    "create_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "cc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myApp.contentcreator",
                    ),
                ),
                (
                    "sp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myApp.sponsor",
                    ),
                ),
            ],
        ),
    ]
