# Generated by Django 4.1 on 2024-05-28 07:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0011_conversation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Conversation",
            new_name="Chatroom",
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("msg", models.TextField(blank=True, null=True)),
                (
                    "create_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myApp.chatroom",
                    ),
                ),
            ],
        ),
    ]
