# Generated by Django 4.1 on 2024-05-28 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0014_alter_message_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
