# Generated by Django 4.1 on 2024-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0016_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="contentLink",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="isAdApproved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="isPaymentComplete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="isSpApproved",
            field=models.BooleanField(default=False),
        ),
    ]
