# Generated by Django 4.1 on 2024-05-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0019_chatroom_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="isPaymentComplete",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="transactionID",
            field=models.TextField(blank=True, null=True),
        ),
    ]
